os:
  - linux
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - 'git clone https://github.com/piface/libmcp23s17.git'
  - cd libmcp23s17/
  - make
  - sudo make install
  - cd ..
  - 'git clone https://github.com/piface/libpifacedigital.git'
  - cd libpifacedigital/
  - make
  - sudo make install
  - cd ..
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@3.2.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
